
language: generic

env: SCIDB_VER=16.9

services:
  - docker

before_install:
  - docker pull rvernica/scidb:${SCIDB_VER}
  - pwd
  - docker run
    --name scidb
    --detach
    --volume /dev/shm
    --tmpfs /dev/shm
    --volume `pwd`:/shim
    --publish 8080:8080
    rvernica/scidb:${SCIDB_VER}
  - while ! curl http://localhost:8080/version; do sleep 1; done
  - docker exec scidb service shimsvc stop

install:
  - docker exec scidb apt-get update
  - docker exec scidb apt-get install
    --assume-yes
    --no-install-recommends
    bc
    busybox-syslogd
    curl
  - docker exec scidb ln --symbolic
    /opt/scidb/16.9/lib/libscidbclient.so /lib/
  - docker exec scidb make --directory /shim install
  - docker exec scidb /sbin/syslogd -n -S -O /dev/stdout &

script:
  - docker exec scidb make --directory /shim test

after_failure:
  - docker logs scidb
